# Generated by Django 4.1.5 on 2023-01-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(default='something', max_length=255),
            preserve_default=False,
        ),
    ]
